onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  axios@<1.12.0: '>=1.12.0'
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  devalue@<5.3.2: '>=5.3.2'
  devalue@<=5.6.2: '>=5.6.3'
  diff@<8.0.3: '>=8.0.3'
  fast-xml-parser@>=4.1.3 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  fast-xml-parser@>=5.0.9 <=5.3.3: '>=5.3.4'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  undici@<6.23.0: '>=6.23.0'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
