onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  axios@<1.12.0: '>=1.12.0'
  devalue@<5.3.2: '>=5.3.2'
  diff@<8.0.3: '>=8.0.3'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  undici@<6.23.0: '>=6.23.0'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
